# Generated by Django 6.0.7 on 2026-07-22 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=100, unique=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
                'ordering': ['nama_kategori'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_supplier', models.CharField(max_length=150)),
                ('kontak', models.CharField(max_length=20)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nama_supplier'],
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_produk', models.CharField(max_length=20, unique=True)),
                ('nama_produk', models.CharField(max_length=150)),
                ('harga_beli', models.DecimalField(decimal_places=2, max_digits=12)),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('stok_minimum', models.PositiveIntegerField(default=5)),
                ('satuan', models.CharField(default='pcs', max_length=20)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='produk/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produk', to='produk.kategori')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produk', to='produk.supplier')),
            ],
            options={
                'ordering': ['nama_produk'],
            },
        ),
        migrations.CreateModel(
            name='StokMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('harga_beli_saat_ini', models.DecimalField(decimal_places=2, max_digits=12)),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_stok_masuk', to='produk.produk')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_stok', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stok Masuk',
                'verbose_name_plural': 'Stok Masuk',
                'ordering': ['-tanggal'],
            },
        ),
    ]
