# Generated by Django 6.0.7 on 2026-07-22 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_transaksi', models.CharField(blank=True, max_length=20, unique=True)),
                ('total_harga', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('metode_bayar', models.CharField(choices=[('tunai', 'Tunai'), ('transfer', 'Transfer'), ('qris', 'QRIS')], default='tunai', max_length=10)),
                ('status', models.CharField(choices=[('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='selesai', max_length=15)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('kasir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi_penjualan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Penjualan',
                'verbose_name_plural': 'Penjualan',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='DetailPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=14)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail_penjualan', to='produk.produk')),
                ('penjualan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='transaksi.penjualan')),
            ],
            options={
                'verbose_name': 'Detail Penjualan',
                'verbose_name_plural': 'Detail Penjualan',
            },
        ),
        migrations.CreateModel(
            name='Retur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('alasan', models.CharField(choices=[('rusak', 'Barang Rusak'), ('salah_kirim', 'Salah Kirim'), ('tidak_sesuai', 'Tidak Sesuai Pesanan'), ('lainnya', 'Lainnya')], default='lainnya', max_length=15)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('diproses_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retur_diproses', to=settings.AUTH_USER_MODEL)),
                ('penjualan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retur', to='transaksi.penjualan')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retur', to='produk.produk')),
            ],
            options={
                'verbose_name_plural': 'Retur',
                'ordering': ['-tanggal'],
            },
        ),
    ]
